/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DataLaporan;

import DataPelanggan.*;
import DataSatuan.*;
import DataKategori.*;
import DataBarang.*;
import Transaksi.*;
import Koneksi.koneksiOracle;
import java.awt.Color;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author basisb12
 */
public class GuiLaporan extends javax.swing.JFrame {

    public CenterRenderer tengah = new CenterRenderer();
    /**
     * Creates new form LaporanKartuStok
     */
    public GuiLaporan() {
        initComponents();
        tampilLaporan();
        lebarKolom();
        this.setLocationRelativeTo(null);
        this.setTitle("DAFTAR SELURUH PINJAMAN");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tglMulai = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        tglKembali = new com.toedter.calendar.JDateChooser();
        tombolCari = new javax.swing.JButton();
        tombolCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellaporan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Dari tanggal");

        tglMulai.setDateFormatString("d-MMM-yyyy");
        tglMulai.setMinSelectableDate(new java.util.Date(-62135791110000L));

        jLabel2.setText("Sampai");

        tglKembali.setDateFormatString("d-MMM-yyyy");

        tombolCari.setText("LIHAT");
        tombolCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCariActionPerformed(evt);
            }
        });

        tombolCetak.setText("CETAK");
        tombolCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolCari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolCetak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tglKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tglMulai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tombolCari)
                        .addComponent(tombolCetak)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabellaporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabellaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabellaporan);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel3.setText("LAPORAN RENTAL BARANG");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addGap(324, 324, 324))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCariActionPerformed
        try {
            // TODO add your handling code here:
            DateFormat sf = new SimpleDateFormat("yyyy/MM/dd");
            Date a= tglMulai.getDate();
            Date b= tglKembali.getDate();
            String ax= sf.format(a);
            String bx= sf.format(b);
            System.out.println(ax);
            System.out.println(a);
            List<Transaksi> l = Laporan_Kontrol.getkoneksi().getAllLaporan(a,b);
            TabelModel_Laporan model = new TabelModel_Laporan(l);
           tabellaporan.setModel(model);
            lebarKolom();
        } catch (SQLException ex) {
            Logger.getLogger(GuiLaporan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tombolCariActionPerformed

    private void tombolCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCetakActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            tabellaporan.setVisible(false);
            
             String namafile = "Laporan.jasper";
            Map<String, Object> params = new HashMap<String, Object>();
            params.put("tgl1", tglMulai.getDate());
            params.put("tgl2", tglKembali.getDate());
            JasperPrint jasperPrint = JasperFillManager.fillReport(namafile,params, new koneksiOracle().getKoneksiOracleDB());
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "File tidak ditemukan");
        }
    }//GEN-LAST:event_tombolCetakActionPerformed

    public void tampilLaporan() {
        try {
            List<Transaksi> list = Laporan_Kontrol.getkoneksi().getAllLaporan();
            TabelModel_Laporan model = new TabelModel_Laporan(list);
            tabellaporan.setModel(model);
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }
    
    public void lebarKolom() {//untuk mengatur lebar kolom dan mengatur isi tabel rata tengah
        TableColumn column;
        tabellaporan.setVisible(true);
        tabellaporan.setShowGrid(true); //memumculkan grid pada table
        tabellaporan.setShowHorizontalLines(true); //menampilkan garis tabel menurun
        tabellaporan.setShowVerticalLines(true); //menampilkan garis tabel mendatar
        tabellaporan.setGridColor(Color.BLACK); //memberi warna garis table
        tabellaporan.getColumnModel().getColumn(0).setCellRenderer(tengah);
        tabellaporan.getColumnModel().getColumn(1).setCellRenderer(tengah);
        tabellaporan.getColumnModel().getColumn(2).setCellRenderer(tengah);
        tabellaporan.getColumnModel().getColumn(3).setCellRenderer(tengah);
        tabellaporan.getColumnModel().getColumn(4).setCellRenderer(tengah);
        tabellaporan.getColumnModel().getColumn(5).setCellRenderer(tengah);
        tabellaporan.getColumnModel().getColumn(6).setCellRenderer(tengah);
        tabellaporan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tabellaporan.getColumnModel().getColumn(0);
        column.setPreferredWidth(40);
        column = tabellaporan.getColumnModel().getColumn(1);
        column.setPreferredWidth(330);
        column = tabellaporan.getColumnModel().getColumn(2);
        column.setPreferredWidth(100);
        column = tabellaporan.getColumnModel().getColumn(3);
        column.setPreferredWidth(161);
        column = tabellaporan.getColumnModel().getColumn(4);
        column.setPreferredWidth(100);
        column = tabellaporan.getColumnModel().getColumn(5);
        column.setPreferredWidth(90);
        column = tabellaporan.getColumnModel().getColumn(6);
        column.setPreferredWidth(190);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new GuiLaporan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabellaporan;
    private com.toedter.calendar.JDateChooser tglKembali;
    private com.toedter.calendar.JDateChooser tglMulai;
    private javax.swing.JButton tombolCari;
    private javax.swing.JButton tombolCetak;
    // End of variables declaration//GEN-END:variables
}
