/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import DataPelanggan.KontrolPelanggan;
import DataPelanggan.Pelanggan;
import DataPelanggan.TabelModel_Pelanggan;
import Databarang.Barang;
import Databarang.KontrolBarang;
import Databarang.TabelModel_Barang;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus a455l
 */
public class Gui_Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Gui_Transaksi
     */
    public Gui_Transaksi() {

        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        DialogBarang.setVisible(false);
        DialogBarang.setLocationRelativeTo(null);
        DialogBarang.setSize(700, 400);
        DialogBarang.setTitle("DAFTAR SELURUH BARANG");

        DialogPelanggan.setVisible(false);
        DialogPelanggan.setLocationRelativeTo(null);
        DialogPelanggan.setSize(700, 400);
        DialogPelanggan.setTitle("DAFTAR SELURUH PELANGGAN");

        DialogTransaksiRental.setVisible(false);
        DialogTransaksiRental.setLocationRelativeTo(null);
        DialogTransaksiRental.setSize(700, 400);
        DialogTransaksiRental.setTitle("DAFTAR SELURUH RENTAL");
        GregorianCalendar gc = new GregorianCalendar();
        SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yy");
//        String kodemasuk = "M-" + sf.format(gc.getTime()) + "-";
//        String kodekeluar = "K-" + sf.format(gc.getTime()) + "-";
        kalender.setDate(gc.getTime());
        label_Bantu_idDetailTransaksi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogPelanggan = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_pelanggan = new javax.swing.JTable();
        DialogBarang = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        DialogTransaksiRental = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_RENTAL = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FieldNamaPelanggan = new javax.swing.JTextField();
        FieldNOTelp = new javax.swing.JTextField();
        buttonCariIDPelanggan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        FieldIDPelanggan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        buttonHapusTransaksi = new javax.swing.JButton();
        buttonTambahRental = new javax.swing.JButton();
        fieldIDTransaksiRental = new javax.swing.JTextField();
        fieldKodeBarang = new javax.swing.JTextField();
        buttonCariBarang = new javax.swing.JButton();
        fieldNamaBarang = new javax.swing.JTextField();
        fieldLamaRental = new javax.swing.JTextField();
        fieldJumlahRental = new javax.swing.JTextField();
        fieldTotalHarga = new javax.swing.JTextField();
        label_Bantu_idDetailTransaksi = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_transaksi = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fieldJaminan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        kalender = new com.toedter.calendar.JDateChooser();
        buttonSimpan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonList = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();
        PRINT = new javax.swing.JButton();

        DialogPelanggan.setModal(true);
        DialogPelanggan.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("DAFTAR SELURUH PELANGGAN"));

        tabel_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pelangganMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_pelanggan);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DialogPelangganLayout = new javax.swing.GroupLayout(DialogPelanggan.getContentPane());
        DialogPelanggan.getContentPane().setLayout(DialogPelangganLayout);
        DialogPelangganLayout.setHorizontalGroup(
            DialogPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(DialogPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DialogPelangganLayout.setVerticalGroup(
            DialogPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
            .addGroup(DialogPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DialogPelangganLayout.createSequentialGroup()
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        DialogBarang.setModal(true);
        DialogBarang.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("DAFTAR SELURUH BARANG"));

        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_barang);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DialogBarangLayout = new javax.swing.GroupLayout(DialogBarang.getContentPane());
        DialogBarang.getContentPane().setLayout(DialogBarangLayout);
        DialogBarangLayout.setHorizontalGroup(
            DialogBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(DialogBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DialogBarangLayout.setVerticalGroup(
            DialogBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
            .addGroup(DialogBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DialogBarangLayout.createSequentialGroup()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        DialogTransaksiRental.setModal(true);
        DialogTransaksiRental.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("DAFTAR SELURUH RENTAL"));

        tabel_RENTAL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_RENTAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_RENTALMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabel_RENTAL);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DialogTransaksiRentalLayout = new javax.swing.GroupLayout(DialogTransaksiRental.getContentPane());
        DialogTransaksiRental.getContentPane().setLayout(DialogTransaksiRentalLayout);
        DialogTransaksiRentalLayout.setHorizontalGroup(
            DialogTransaksiRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(DialogTransaksiRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DialogTransaksiRentalLayout.setVerticalGroup(
            DialogTransaksiRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
            .addGroup(DialogTransaksiRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DialogTransaksiRentalLayout.createSequentialGroup()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANSAKSI BARANG");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("ID Pelanggan :");

        jLabel2.setText("Pelanggan : ");

        buttonCariIDPelanggan.setText("CARI");
        buttonCariIDPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariIDPelangganActionPerformed(evt);
            }
        });

        jLabel3.setText("TELP");

        FieldIDPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldIDPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldIDPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCariIDPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(FieldNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(FieldNOTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonCariIDPelanggan)
                        .addComponent(FieldIDPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(FieldNOTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("ID Transaksi Rental :");

        jLabel5.setText("Kode Barang :");

        jLabel6.setText("Nama Barang :");

        jLabel7.setText("Jumlah Rental :");

        jLabel8.setText("Lama Rental :");

        jLabel9.setText("Total Harga :");

        buttonHapusTransaksi.setText("HAPUS");
        buttonHapusTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusTransaksiActionPerformed(evt);
            }
        });

        buttonTambahRental.setText("TAMBAH");
        buttonTambahRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahRentalActionPerformed(evt);
            }
        });

        buttonCariBarang.setText("CARI");
        buttonCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariBarangActionPerformed(evt);
            }
        });

        fieldLamaRental.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldLamaRentalKeyTyped(evt);
            }
        });

        fieldJumlahRental.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldJumlahRentalKeyTyped(evt);
            }
        });

        label_Bantu_idDetailTransaksi.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addComponent(jLabel8))
                            .addGap(33, 33, 33)))
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonTambahRental)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapusTransaksi))
                    .addComponent(fieldTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldIDTransaksiRental, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fieldKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_Bantu_idDetailTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fieldNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldJumlahRental, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldLamaRental, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 259, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addComponent(fieldIDTransaksiRental, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCariBarang)
                    .addComponent(jLabel5)
                    .addComponent(label_Bantu_idDetailTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldJumlahRental, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fieldLamaRental, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(fieldTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambahRental)
                    .addComponent(buttonHapusTransaksi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Barang"));

        tabel_transaksi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tabel_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Barang", "Jumlah", "Lama Rental", "Total Harga"
            }
        ));
        tabel_transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabel_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_transaksiMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabel_transaksiMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_transaksi);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("Jaminan Rental");

        jLabel11.setText("Tanggal");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldJaminan, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(fieldJaminan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        buttonSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483718_Save.png"))); // NOI18N
        buttonSimpan.setText("SIMPAN");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483766_Delete.png"))); // NOI18N
        buttonHapus.setText("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483845_Copy.png"))); // NOI18N
        buttonList.setText("LIST");
        buttonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListActionPerformed(evt);
            }
        });

        buttonBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483766_Delete.png"))); // NOI18N
        buttonBatal.setText("BATAL");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        buttonKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442484041_exit.png"))); // NOI18N
        buttonKeluar.setText("KELUAR");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        PRINT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1442483829_Print.png"))); // NOI18N
        PRINT.setText("PRINT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonList)
                        .addGap(18, 18, 18)
                        .addComponent(PRINT)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonKeluar)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonHapus)
                    .addComponent(buttonList)
                    .addComponent(buttonBatal)
                    .addComponent(buttonKeluar)
                    .addComponent(PRINT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String namatombol = buttonSimpan.getText();
            Date tgl = kalender.getDate();
            String idPelanggan = FieldIDPelanggan.getText();
            Pelanggan p = new Pelanggan();
            p.setKode(idPelanggan);

            int jumBrg = Kontrol_DetailTransaksi.getkoneksi().jumlahBarangDataDetailTransaksi(fieldIDTransaksiRental.getText());
            long totalHarga = Kontrol_DetailTransaksi.getkoneksi().totalHargaDataDetailTransaksi(fieldIDTransaksiRental.getText());
            String jaminan = fieldJaminan.getText();

            Transaksi tr = new Transaksi();
            tr.setIdTransaksi(fieldIDTransaksiRental.getText());
            tr.setTanggal(tgl);
            tr.setIdPelangan(p);
            tr.setJumlahBarang(jumBrg);
            tr.setTotalHarga(totalHarga);
            tr.setJaminan(jaminan);
            Kontrol_Transaksi trk = Kontrol_Transaksi.getKoneksi();
            if (buttonSimpan.getText().equals("SIMPAN")) {
                trk.InsertTransaksi(tr);
                JOptionPane.showMessageDialog(rootPane, "Tersimpan");
            } else {
                trk.UpdateTransaksi(tr);
                JOptionPane.showMessageDialog(rootPane, "Terupdate");
            }
            refresh();
        } catch (SQLException ex) {
            ex.getMessage();
        }


    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        if (fieldIDTransaksiRental.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang dihapus");
        } else {
            Kontrol_Transaksi k = Kontrol_Transaksi.getKoneksi();
            k.DeleteTransaksi(fieldIDTransaksiRental.getText());
            JOptionPane.showMessageDialog(null, "Terhapus");
            refresh();
        }
        fieldIDTransaksiRental.setText("");
        fieldJumlahRental.setEnabled(true);
        fieldJumlahRental.setText("0");
        fieldNamaBarang.setText("");
        buttonHapus.setEnabled(false);

    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListActionPerformed
        tampilRental();
        DialogTransaksiRental.setLocationRelativeTo(null);
        DialogTransaksiRental.setVisible(true);

    }//GEN-LAST:event_buttonListActionPerformed

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void buttonCariIDPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariIDPelangganActionPerformed
        // TODO add your handling code here:
        tampilPelanggan();
        DialogPelanggan.setLocationRelativeTo(null);
        DialogPelanggan.setVisible(true);
    }//GEN-LAST:event_buttonCariIDPelangganActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void fieldJumlahRentalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldJumlahRentalKeyTyped
        // TODO add your handling code here:
        char kar = evt.getKeyChar();
        if (!(Character.isDigit(kar) || kar == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_fieldJumlahRentalKeyTyped

    private void fieldLamaRentalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldLamaRentalKeyTyped
        // TODO add your handling code here:
        char kar = evt.getKeyChar();
        if (!(Character.isDigit(kar) || kar == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_fieldLamaRentalKeyTyped
    public void tampilPelanggan() {
        List<Pelanggan> brg = KontrolPelanggan.getKoneksi().tampilPelanggan();//            Logger.getLogger(View_Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        TabelModel_Pelanggan model = new TabelModel_Pelanggan(brg);
        tabel_pelanggan.setModel(model);
    }

    public void tampilBarang() {
        List<Barang> brg = KontrolBarang.getKoneksi().tampilDataBarang();
        TabelModel_Barang model = new TabelModel_Barang(brg);
        tabel_barang.setModel(model);
    }


    private void tabel_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pelangganMouseClicked
        // TODO add your handling code here:
        int row = tabel_pelanggan.getSelectedRow();
        String kode = tabel_pelanggan.getValueAt(row, 1).toString();
        String namaPelanggan = tabel_pelanggan.getValueAt(row, 2).toString();
        String telp = tabel_pelanggan.getValueAt(row, 4).toString();
        FieldIDPelanggan.setText(kode);
        FieldNamaPelanggan.setText(namaPelanggan);
        FieldNOTelp.setText(telp);
        DialogPelanggan.setVisible(false);
        KodeOtomatisRental();
        buttonCariBarang.setEnabled(true);
        tampilDetailTransaksi(fieldIDTransaksiRental.getText());
    }//GEN-LAST:event_tabel_pelangganMouseClicked

    private void buttonCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariBarangActionPerformed
        tampilBarang();
        DialogBarang.setLocationRelativeTo(null);
        DialogBarang.setVisible(true);
    }//GEN-LAST:event_buttonCariBarangActionPerformed

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
        int row = tabel_barang.getSelectedRow();
        String kode = tabel_barang.getValueAt(row, 1).toString();
        String namaBarang = tabel_barang.getValueAt(row, 2).toString();
        fieldKodeBarang.setText(kode);
        fieldNamaBarang.setText(namaBarang);
        DialogBarang.setVisible(false);
        fieldJumlahRental.setEditable(true);
        fieldLamaRental.setEditable(true);
    }//GEN-LAST:event_tabel_barangMouseClicked

    private void tabel_RENTALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_RENTALMouseClicked
        try {
            // TODO add your handling code here:
            int row = tabel_RENTAL.getSelectedRow();
            String ID_RENTAL = tabel_RENTAL.getValueAt(row, 1).toString();
            Date TANGGAL = (Date) tabel_RENTAL.getValueAt(row, 2);
            String ID_PELANGGAN = tabel_RENTAL.getValueAt(row, 3).toString();
            String JUMLAH = tabel_RENTAL.getValueAt(row, 4).toString();
            String HARGA = tabel_RENTAL.getValueAt(row, 5).toString();
            String JAMINAN = tabel_RENTAL.getValueAt(row, 6).toString();
            fieldIDTransaksiRental.setText(ID_RENTAL);
            Transaksi r = new Transaksi();
            r.setIdTransaksi(ID_RENTAL);
//        int indek = Rental.cari(r);
            fieldJaminan.setText(JAMINAN);
            kalender.setDate(TANGGAL);
            Pelanggan p = new Pelanggan();
            Pelanggan pel = KontrolPelanggan.getKoneksi().CariPelanggan(ID_PELANGGAN);
//        p.setId(Rental.getDataRental().get(indek).getIdPelangan().getId());
//        int id = Pelanggan.cari(p);
            FieldIDPelanggan.setText(ID_PELANGGAN);
            FieldNamaPelanggan.setText(pel.getNama());
            FieldNOTelp.setText(pel.getTelp());
//        tampilTransaksi(ID_RENTAL);
            tampilDetailTransaksi(fieldIDTransaksiRental.getText());
            DialogTransaksiRental.setVisible(false);
            buttonCariBarang.setEnabled(true);
            buttonSimpan.setText("UPDATE");
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_tabel_RENTALMouseClicked

    private void buttonTambahRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahRentalActionPerformed
        try {
            // TODO add your handling code here:
            String namatombol = buttonTambahRental.getText();
            String idTransaksiRental = fieldIDTransaksiRental.getText();
            int jumlahBarang = Integer.parseInt(fieldJumlahRental.getText());
            int lama = Integer.parseInt(fieldLamaRental.getText());
            String kode = fieldKodeBarang.getText();

            DetailTransaksi r = new DetailTransaksi();
            r.setId(String.valueOf(Kontrol_DetailTransaksi.getkoneksi().kodeOtomatis()));

            Barang b = new Barang();
            b.setKodeBarang(kode);
            r.setKodebarang(b);

            Transaksi t = new Transaksi();
            t.setIdTransaksi(idTransaksiRental);
            r.setIdTranksai(t);

            r.setJumlahBarang(jumlahBarang);
            r.setLamaPinjam(lama);
            Barang brg = KontrolBarang.getKoneksi().LihatSatuBarang(kode);
            long harga = (long) (lama * brg.getHargasewa());
            r.setTotalHarga(jumlahBarang * harga);

            if (fieldIDTransaksiRental.getText().equals("") || fieldKodeBarang.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Silahkan masukkan data dengan benar");
            } else {
                Kontrol_DetailTransaksi kon = Kontrol_DetailTransaksi.getkoneksi().getkoneksi();

                if (namatombol.equals("UPDATE")) {
                    r.setId(label_Bantu_idDetailTransaksi.getText());
                    kon.UpdateDetailTransaksi(r);

                    fieldNamaBarang.setText("");
                    fieldJumlahRental.setText("0");
                    fieldLamaRental.setText("0");
                    fieldKodeBarang.setText("");
                    buttonTambahRental.setText("TAMBAH");

                    fieldLamaRental.setEditable(false);
                    fieldJumlahRental.setEditable(false);

                } else {
                    kon.InsertDetailTransaksi(r);

                    fieldNamaBarang.setText("");
                    fieldJumlahRental.setText("0");
                    fieldLamaRental.setText("0");
                    fieldKodeBarang.setText("");

                    fieldLamaRental.setEditable(false);
                    fieldJumlahRental.setEditable(false);
                }

                tampilDetailTransaksi(fieldIDTransaksiRental.getText());

            }
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_buttonTambahRentalActionPerformed

    private void tabel_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_transaksiMouseClicked
        try {
            // TODO add your handling code here:
            int row = tabel_transaksi.getSelectedRow();
            String id = tabel_transaksi.getValueAt(row, 1).toString();
            DetailTransaksi d = Kontrol_DetailTransaksi.getkoneksi().LihatSatuBarang(id);
            label_Bantu_idDetailTransaksi.setText(id);

            fieldKodeBarang.setText(d.getKodebarang().getKodeBarang());
            fieldNamaBarang.setText(d.getKodebarang().getNamaBarang());
            fieldJumlahRental.setText(String.valueOf(d.getJumlahBarang()));
            fieldLamaRental.setText(String.valueOf(d.getLamaPinjam()));

            buttonTambahRental.setText("UPDATE");
            buttonHapusTransaksi.setEnabled(true);
        } catch (SQLException ex) {
            ex.getMessage();
        }

    }//GEN-LAST:event_tabel_transaksiMouseClicked

    private void tabel_transaksiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_transaksiMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_transaksiMouseReleased

    private void buttonHapusTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusTransaksiActionPerformed
        if (!label_Bantu_idDetailTransaksi.getText().equals("")) {
            try {
                Kontrol_DetailTransaksi.getkoneksi().DeleteDetailTransaksi(label_Bantu_idDetailTransaksi.getText());
                tampilDetailTransaksi(fieldIDTransaksiRental.getText());
                buttonHapusTransaksi.setEnabled(false);
                buttonTambahRental.setText("TAMBAH");
            } catch (SQLException ex) {
                ex.getMessage();
            }
        }
    }//GEN-LAST:event_buttonHapusTransaksiActionPerformed

    private void FieldIDPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldIDPelangganActionPerformed
        try {
            // TODO add your handling code here:
            Pelanggan pel = KontrolPelanggan.getKoneksi().CariPelanggan(FieldIDPelanggan.getText());
            if (!pel.getNama().equals("")) {
                FieldNamaPelanggan.setText(pel.getNama());
                FieldNOTelp.setText(pel.getTelp());
            } else {
                FieldNamaPelanggan.setText("");
                FieldNOTelp.setText("");
            }
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_FieldIDPelangganActionPerformed
    public void KodeOtomatisRental() {
        try {
            GregorianCalendar gc = new GregorianCalendar();
            SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yy");
            String kp = FieldIDPelanggan.getText();
            String kodemasuk = "YULIUS/RENTALBARANG/KELUAR/" + kp + "/" + sf.format(gc.getTime()) + "/";
            Date tgl = new Date();
            Date ask = new java.sql.Date(tgl.getTime());
            SimpleDateFormat fformat = new SimpleDateFormat("dd-MMM-yy");
            String awal = fformat.format(ask);
            String bantu;
            int kode;
            kode = Kontrol_Transaksi.getKoneksi().kodeOtomatis(new java.sql.Date(tgl.getTime()), kp) + 1;
//            System.out.println(sf.format(ask));
//            System.out.println(sf.format(gc.getTime()));
//            System.out.println(awal);
            System.out.println(new java.sql.Date(tgl.getTime()));
            if (kode == 1) {
                bantu = "001";
                fieldIDTransaksiRental.setText(kodemasuk + bantu);
            } else if (kode < 10) {
                bantu = "00";
                fieldIDTransaksiRental.setText(kodemasuk + bantu + Integer.toString(kode));
            } else if (10 <= kode && kode < 100) {
                bantu = "0";
                fieldIDTransaksiRental.setText(kodemasuk + bantu + Integer.toString(kode));
            } else {
                fieldIDTransaksiRental.setText(kodemasuk + Integer.toString(kode));
            }
        } catch (SQLException ex) {
            ex.getMessage();
        }

    }

    public void tampilRental() {
        try {
            List<Transaksi> trans = Kontrol_Transaksi.getKoneksi().tampilDataTransaksi();
            TabelModel_Transaksi model = new TabelModel_Transaksi(trans);
            tabel_RENTAL.setModel(model);
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }

    public void tampilDetailTransaksi(String idrental) {
        try {
            List<DetailTransaksi> brg = Kontrol_DetailTransaksi.getkoneksi().tampilDataDetailTransaksi(idrental);
            TabelModel_DetailTransaksi model = new TabelModel_DetailTransaksi(brg);
            tabel_transaksi.setModel(model);
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }

    public void refresh() {
        FieldIDPelanggan.setText("");
        FieldNOTelp.setText("");
        FieldNOTelp.setText("");
        fieldIDTransaksiRental.setText("");
        fieldKodeBarang.setText("");
        fieldNamaBarang.setText("");
        fieldJumlahRental.setText("0");
        fieldLamaRental.setText("0");
        fieldTotalHarga.setText("0");
        fieldJaminan.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogBarang;
    private javax.swing.JDialog DialogPelanggan;
    private javax.swing.JDialog DialogTransaksiRental;
    private javax.swing.JTextField FieldIDPelanggan;
    private javax.swing.JTextField FieldNOTelp;
    private javax.swing.JTextField FieldNamaPelanggan;
    private javax.swing.JButton PRINT;
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonCariBarang;
    private javax.swing.JButton buttonCariIDPelanggan;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonHapusTransaksi;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonList;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonTambahRental;
    private javax.swing.JTextField fieldIDTransaksiRental;
    private javax.swing.JTextField fieldJaminan;
    private javax.swing.JTextField fieldJumlahRental;
    private javax.swing.JTextField fieldKodeBarang;
    private javax.swing.JTextField fieldLamaRental;
    private javax.swing.JTextField fieldNamaBarang;
    private javax.swing.JTextField fieldTotalHarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.calendar.JDateChooser kalender;
    private javax.swing.JLabel label_Bantu_idDetailTransaksi;
    private javax.swing.JTable tabel_RENTAL;
    private javax.swing.JTable tabel_barang;
    private javax.swing.JTable tabel_pelanggan;
    private javax.swing.JTable tabel_transaksi;
    // End of variables declaration//GEN-END:variables
}
